name: rna_folding
channels:
  - anaconda
  - pytorch
  - fastai
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.6.0
  - asttokens=2.0.5
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.2.25
  - catalogue=2.0.10
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - comm=0.2.1
  - confection=0.1.4
  - contourpy=1.2.1
  - cramjam=2.9.1
  - cudatoolkit=11.1.1
  - cycler=0.11.0
  - cymem=2.0.6
  - cython-blis=0.7.9
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.4
  - fastai=2.7.17
  - fastcore=1.7.20
  - fastdownload=0.0.7
  - fastparquet=2024.11.0
  - fastprogress=1.0.0
  - ffmpeg=4.3
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.10.4
  - fsspec=2024.12.0
  - gflags=2.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.7.1
  - gmp=6.3.0
  - gnutls=3.6.13
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - jbig=2.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=2.2.1
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libdeflate=1.7
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libhwloc=2.8.0
  - libiconv=1.18
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnghttp2=1.57.0
  - libparquet=16.1.0
  - libpng=1.6.37
  - libpq=12.20
  - libprotobuf=4.25.3
  - libre2-11=2024.02.01
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.19.0
  - libtiff=4.3.0
  - libutf8proc=2.8.0
  - libuuid=1.41.5
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - murmurhash=1.0.12
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.6
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - olefile=0.47
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.4.1
  - orc=2.0.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=25.0
  - platformdirs=3.10.0
  - ply=3.11
  - preshed=3.0.6
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pybind11-abi=4
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.15.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=1.10.1
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.2
  - re2=2024.02.01
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - s2n=1.4.15
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=75.8.0
  - shellingham=1.5.0
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - snappy=1.2.1
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.45.3
  - srsly=2.5.1
  - stack_data=0.2.0
  - tbb=2021.8.0
  - thinc=8.2.2
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tomli=2.0.1
  - torchaudio=0.10.1
  - torchvision=0.11.2
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.9.0
  - typing-extensions=4.13.0
  - typing_extensions=4.13.0
  - tzdata=2025a
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - weasel=0.3.4
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
