# Model hyperparameters
learning_rate: 0.001  # The learning rate for the optimizer
batch_size: 2        # Number of samples per batch
test_batch_size: 8        # Number of samples per batch
epochs: 200            # Total training epochs
#optimizer: "ranger"       # Optimization algorithm
dropout: 0.05     # Dropout regularization rate
weight_decay: 0.0001
k: 5
ninp: 256
nlayers: 9
nclass: 3 # 今回、x,y,zの3値を予測することが確定ゆえ、このハイパラは固定
ntoken: 5 #AUGC + padding/N token
nhead: 16
max_len: 512

#use_bpp: False
use_flip_aug: true
max_len_filter: 9999999999999
min_len_filter: 10
#bpp_file_folder: "../../input/bpp_files/"
gradient_accumulation_steps: 1
use_triangular_attention: false
pairwise_dimension: 64


cutoff_date: "2000-01-01"
test_cutoff_date: "2000-04-01"


#Data scaling
use_data_percentage: 1
use_dirty_data: true # turn off for data scaling and data dropout experiments

# Other configurations
fold: 0
nfolds: 6
input_dir: "../../input/stanford-rna-3d-folding"
gpu_id: "0"
